### ISSUE TITLE
SPM Warnings

### ISSUE THREAD

**Issue by ikorich** [zevwings/ZVProgressHUD#11]
Hey @zevwings ,

can you update platform version to - platforms: [.iOS(.v9)]?

`
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99.
`

same issue for ZVActivityIndicatorView

**Comment by ikorich** [comment]
please check ios usage statistic - https://david-smith.org/iosversionstats/

**Comment by zevwings** [comment]
Fix @V3.0.4, thx.
