### ISSUE TITLE
Dependency "ZVProgressHUD" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by nirvana72** [zevwings/ZVProgressHUD#3]
*** Cloning AlamofireImage
*** Cloning ZVProgressHUD
*** Cloning SnapKit
*** Cloning SwiftyJSON
*** Cloning Alamofire
*** Checking out Alamofire at "4.8.2"
*** Checking out SwiftyJSON at "4.3.0"
*** Checking out SnapKit at "4.2.0"
*** Checking out ZVProgressHUD at "0.0.2"
*** Checking out AlamofireImage at "3.5.2"
*** xcodebuild output can be found in /var/folders/f3/lsvwk9b125q5w2mhrpj54__80000gn/T/carthage-xcodebuild.gjNf3B.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "AlamofireImage iOS" in AlamofireImage.xcworkspace
*** Building scheme "SnapKit" in SnapKit.xcworkspace
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Skipped building ZVProgressHUD due to the error:
Dependency "ZVProgressHUD" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/zevwings/ZVProgressHUD/issues/new
nijiadeMBP:myapp nijia$

**Comment by zevwings** [comment]
You can use the version 2.1.0 to fix this.

**Comment by zevwings** [comment]
You can use the version 2.1.0 to fix this.
```
github "zevwings/ZVProgressHUD" ~> 2.1.0
```
