### ISSUE TITLE
Error in Xcode 11 with SwiftPM integration

### ISSUE THREAD

**Issue by imvenj** [zevwings/ZVProgressHUD#4]
I tried to add ZVProgressHUD with SwiftPM integration in Xcode 11, but got an error while compiling.

```
Use of undeclared type 'UIView'
```

![Screen Shot 2019-10-13 at 10 00 50](https://user-images.githubusercontent.com/844773/66709940-e855d400-eda0-11e9-9e65-8980488f309c.png)

ZVProgressHUD works fine using Carthage. Please look into it. Thank you.

**Comment by zevwings** [comment]
tks. this error will fixed at 2.4.5, this version is release now.

**Comment by zevwings** [comment]
> I tried to add ZVProgressHUD with SwiftPM integration in Xcode 11, but got an error while compiling.
> 
> ```
> Use of undeclared type 'UIView'
> ```
> 
> ![Screen Shot 2019-10-13 at 10 00 50](https://user-images.githubusercontent.com/844773/66709940-e855d400-eda0-11e9-9e65-8980488f309c.png)
> 
> ZVProgressHUD works fine using Carthage. Please look into it. Thank you.
